name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  #  Change to your AWS region

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Refresh Terraform State
        run: terraform refresh
        working-directory: terraform

      - name: Debug Terraform Output
        run: terraform output webserver_ip
        working-directory: terraform
          
      - name: Get Webserver IP
        run: |
            # Attempt to get raw output first, fall back to the formatted version if necessary
            WEBSERVER_IP=$(terraform output -raw webserver_ip)
            
            # If WEBSERVER_IP was set, add it to the GitHub environment variables
            if [[ -n "$WEBSERVER_IP" ]]; then
              echo "WEBSERVER_IP=$WEBSERVER_IP" >> $GITHUB_ENV
            else
              echo "Error: Unable to retrieve webserver IP."
              exit 1
            fi
        shell: bash
        working-directory: terraform
        
      - name: Update Ansible Inventory
        run: |
          echo "[webserver]" > ansible/inventory.ini
          echo "$WEBSERVER_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini

      - name: Wait for SSH to be Available
        run: |
          echo "Waiting for SSH on $WEBSERVER_IP..."
          until nc -zv $WEBSERVER_IP 22; do sleep 5; done
          echo "SSH is ready!"

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/ansible_playbook.yml

